name: TEMP Delete old backup

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/temp-delete-old-backup.yml"

permissions:
  contents: write

jobs:
  delete-old-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old backup branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -X DELETE "repos/${GITHUB_REPOSITORY}/git/refs/heads/RECUPERACAO-CASO-CHAT-FACA-MERDA"
